### ISSUE TITLE
Add node 0.12.9 for DDOS prevention

### ISSUE THREAD

**Issue by georgephillips** [cusspvz/node.docker#5]
https://nodejs.org/en/blog/vulnerability/december-2015-security-releases/

**Comment by cusspvz** [comment]
Thanks for point that out!

I've already updated node versions file, but since I'm with some troubles with docker hub auto build process, I'm build all of them on my laptop.

Hopefully they will be available soon.
You can see latest tag pulls [here](https://hub.docker.com/r/cusspvz/node/tags/).

Closing this up.
