### ISSUE TITLE
[question] Problem with node-sass dep

### ISSUE THREAD

**Issue by efernandesng** [cusspvz/node.docker#9]
Hi,

Alpine Linux is not supported by node-sass sass/node-sass#1589 :( 

You known some simple workaround to mitigate the problem?

**Comment by cusspvz** [comment]
``` Dockerfile
FROM cusspvz/node:5.1.1

RUN \
  apk update && \
  apk add $BUILD_APKS && \
  npm install node-sass && \
  apk del $BUILD_APKS
```

I've built a _Dockerfile_ to test it out and it installed without problems. I think the reason why it works is because my image includes the glibc packages, which aren't included on alpine repos by default. :)

EDIT:

<img width="399" alt="PoC" src="https://cloud.githubusercontent.com/assets/3604053/18852584/02779974-8439-11e6-9de8-1a657daf6daf.png">

<img width="394" alt="captura de ecra 2016-09-26 as 22 32 34" src="https://cloud.githubusercontent.com/assets/3604053/18852620/2939d914-8439-11e6-8b3c-1bcbe9c9b539.png">

**Comment by cusspvz** [comment]
Please re-open in case it won't work for you!
Thanks for using _node.docker_! :)
